app/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menu_app.urls')),
]

menu_app/urls.py
from django.urls import path
from menu_app.views import draw_menu, MenuListView

app_name = 'menu_app'

urlpatterns = [
    path('', MenuListView.as_view(), name='menu-list'),
    path('<str:name>/', draw_menu, name='draw_menu'),
]

menu_app/models.py
from django.db import models


class Menu(models.Model):
    name = models.CharField(max_length=255)
    parent = models.ForeignKey('self', null=True, blank=True, related_name='child', on_delete=models.CASCADE)
    url = models.CharField(max_length=255, unique=True)
    name_url = models.CharField(max_length=255, null=True, blank=True)

    def __str__(self):
        return self.name

menu_app/views.py
from django.shortcuts import render
from menu_app.models import Menu
from django.views.generic import ListView


class MenuListView(ListView):
    model = Menu
    template_name = 'menu_app/menu_list.html'
    context_object_name = 'items'


def draw_menu(request, name):
    return render(request, 'menu_app/menu.html', {'name': name})

templates/menu_app/menu.html
{% load menu_tag %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>Меню</title>

</head>
<body>

{% draw_menu name %}

</body>
</html>

templates/menu_app/menu_list.html
{% for item in items %}
    <ul><li><a href="{% url 'menu_app:draw_menu' name=item.url %}">{{item.name }}</a></ul></li>
{% endfor %}